version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: event_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EventBooking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: event_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: event_booking_app
    ports:
      - "8000:8000"
      - "8501:8501"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/EventBooking
      REDIS_URL: redis://redis:6379
      SECRET_KEY: super-secret-key
      ADMIN_SETUP_KEY: setup_admin_key
      BASE_URL: http://backend:8000

volumes:
  postgres_data:

